<?php

namespace Database\Seeders;

use App\Models\Subject;
use App\Models\Teacher;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class TeacherSeeder extends Seeder
{
    /**
     * Seed teacher accounts from SMKN 1 Ciamis staff list (Juni 2026).
     * Total: 97 guru (28 PNS + 55 PPPK + 13 GTT/Non-ASN).
     *
     * Idempotent: running multiple times will update existing rows
     * by NIP / email instead of creating duplicates.
     *
     * Notes:
     *  - Password default = NIP masing-masing guru.
     *  - Email dibuat dari nama (tanpa gelar), format: nama.lengkap@guru.sch.id
     *  - phone_number adalah placeholder; sesuaikan dengan data asli jika ada.
     *  - department & subjects dikosongkan; isi sesuai kurikulum sekolah.
     *  - Guru no. 94 & 95 (Maulina Fajrin dan Iqbal Fauzi) memiliki tanggal
     *    lahir sama di data asli; NIP dibuat unik dengan suffix berbeda.
     */
    public function run(): void
    {
        $teachers = [
            [
                'email'         => 'cepy.wahyudin@guru.sch.id',
                'nip'           => '198408252010011010',
                'name'          => 'H. Cepy Wahyudin, A.Md., S.Kom., S.Kom.',
                'gender'        => 'L',
                'date_of_birth' => '1984-08-25',
                'phone_number'  => '081200000001',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'elin.karlinah@guru.sch.id',
                'nip'           => '196806051994122006',
                'name'          => 'Dra. Elin Karlinah',
                'gender'        => 'P',
                'date_of_birth' => '1968-06-05',
                'phone_number'  => '081200000002',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'asep.cahrina@guru.sch.id',
                'nip'           => '196801231994121006',
                'name'          => 'Drs. Asep Cahrina',
                'gender'        => 'L',
                'date_of_birth' => '1968-01-23',
                'phone_number'  => '081200000003',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'nanang.aziz.s@guru.sch.id',
                'nip'           => '196704281990031002',
                'name'          => 'H. Nanang Aziz S., S.Pd.,M.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1967-04-28',
                'phone_number'  => '081200000004',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'cucu.hermawan@guru.sch.id',
                'nip'           => '197401011997021001',
                'name'          => 'H. Cucu Hermawan, M.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1974-01-01',
                'phone_number'  => '081200000005',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'dadang.nurdin@guru.sch.id',
                'nip'           => '196609071994121001',
                'name'          => 'Drs. Dadang Nurdin',
                'gender'        => 'L',
                'date_of_birth' => '1966-09-07',
                'phone_number'  => '081200000006',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'oneng.dalilah@guru.sch.id',
                'nip'           => '196706221991032006',
                'name'          => 'Oneng Dalilah, M.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1967-06-22',
                'phone_number'  => '081200000007',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'dedeh.kurniasih@guru.sch.id',
                'nip'           => '197010091996012001',
                'name'          => 'Dedeh Kurniasih, S.Pd, M.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1970-10-09',
                'phone_number'  => '081200000008',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'yana.hendrayana@guru.sch.id',
                'nip'           => '197105281998021004',
                'name'          => 'Yana Hendrayana, S.Pd. M.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1971-05-28',
                'phone_number'  => '081200000009',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'alisah@guru.sch.id',
                'nip'           => '197204111996012001',
                'name'          => 'Hj. Alisah, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1972-04-11',
                'phone_number'  => '081200000010',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'endah.rahayu.d@guru.sch.id',
                'nip'           => '197207122006042006',
                'name'          => 'Endah Rahayu D, S.Pd. M.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1972-07-12',
                'phone_number'  => '081200000011',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'tika.mustikawati@guru.sch.id',
                'nip'           => '198202102005012008',
                'name'          => 'Tika Mustikawati, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1982-02-10',
                'phone_number'  => '081200000012',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'atin.kudriatin@guru.sch.id',
                'nip'           => '197602292006042009',
                'name'          => 'Atin Kudriatin, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1976-02-29',
                'phone_number'  => '081200000013',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'cucu.cahyani@guru.sch.id',
                'nip'           => '198001102008012006',
                'name'          => 'Cucu Cahyani, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1980-01-10',
                'phone_number'  => '081200000014',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'imas.masriah@guru.sch.id',
                'nip'           => '197903102006042025',
                'name'          => 'Imas Masriah, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1979-03-10',
                'phone_number'  => '081200000015',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'atin.herawati@guru.sch.id',
                'nip'           => '198001192008012006',
                'name'          => 'Hj. Atin Herawati, M.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1980-01-19',
                'phone_number'  => '081200000016',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'kiki.supendi@guru.sch.id',
                'nip'           => '197701202009011007',
                'name'          => 'Kiki Supendi, MT.',
                'gender'        => 'L',
                'date_of_birth' => '1977-01-20',
                'phone_number'  => '081200000017',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'tita.puspita@guru.sch.id',
                'nip'           => '198102252008012006',
                'name'          => 'Tita Puspita, S.Pd., M.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1981-02-25',
                'phone_number'  => '081200000018',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'ikhsan.nur.rokhmat@guru.sch.id',
                'nip'           => '197510112008011004',
                'name'          => 'Ikhsan Nur Rokhmat, S.Pd.,M.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1975-10-11',
                'phone_number'  => '081200000019',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'dadan.sugiarna@guru.sch.id',
                'nip'           => '196608091997021001',
                'name'          => 'Dadan Sugiarna, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1966-08-09',
                'phone_number'  => '081200000020',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'pebi.dinastriani@guru.sch.id',
                'nip'           => '198802052011012004',
                'name'          => 'Pebi Dinastriani, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1988-02-05',
                'phone_number'  => '081200000021',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'irma.sukmarini@guru.sch.id',
                'nip'           => '198212102009012007',
                'name'          => 'Irma Sukmarini, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1982-12-10',
                'phone_number'  => '081200000022',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'hariman.hendriana@guru.sch.id',
                'nip'           => '197708292008011002',
                'name'          => 'Hariman Hendriana, S.Pd.,M.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1977-08-29',
                'phone_number'  => '081200000023',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'carkim@guru.sch.id',
                'nip'           => '197512252014081001',
                'name'          => 'Carkim, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1975-12-25',
                'phone_number'  => '081200000024',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'nastiti@guru.sch.id',
                'nip'           => '198909242014012001',
                'name'          => 'Nastiti, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1989-09-24',
                'phone_number'  => '081200000025',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'ranti.purnama.dewi@guru.sch.id',
                'nip'           => '198909132019032014',
                'name'          => 'Ranti Purnama Dewi, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1989-09-13',
                'phone_number'  => '081200000026',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'dini.yudi.kasimamora@guru.sch.id',
                'nip'           => '199303112020122022',
                'name'          => 'Dini Yudi Kasimamora, S.Tr.Par.',
                'gender'        => 'P',
                'date_of_birth' => '1993-03-11',
                'phone_number'  => '081200000027',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'ani.herliani@guru.sch.id',
                'nip'           => '198009162014082003',
                'name'          => 'Ani Herliani, S.Kom.',
                'gender'        => 'P',
                'date_of_birth' => '1980-09-16',
                'phone_number'  => '081200000028',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'yati.setiawati@guru.sch.id',
                'nip'           => '197608272021212001',
                'name'          => 'Yati Setiawati, S.Ag.',
                'gender'        => 'P',
                'date_of_birth' => '1976-08-27',
                'phone_number'  => '081200000029',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'cahyaman.natawiguna@guru.sch.id',
                'nip'           => '197301312021211002',
                'name'          => 'Cahyaman Natawiguna, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1973-01-31',
                'phone_number'  => '081200000030',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'iip.masripah@guru.sch.id',
                'nip'           => '197408012021212002',
                'name'          => 'Iip Masripah, S.Ag.',
                'gender'        => 'P',
                'date_of_birth' => '1974-08-01',
                'phone_number'  => '081200000031',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'yeyet.rohaeti@guru.sch.id',
                'nip'           => '197501032021212005',
                'name'          => 'Yeyet Rohaeti, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1975-01-03',
                'phone_number'  => '081200000032',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'teti.sri.mulyati.hidayat@guru.sch.id',
                'nip'           => '198211152022212018',
                'name'          => 'Teti Sri Mulyati Hidayat, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1982-11-15',
                'phone_number'  => '081200000033',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'ane.maryani@guru.sch.id',
                'nip'           => '198703162022212007',
                'name'          => 'Ane Maryani, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1987-03-16',
                'phone_number'  => '081200000034',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'ati.sukmawati@guru.sch.id',
                'nip'           => '198806272022212014',
                'name'          => 'Ati Sukmawati, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1988-06-27',
                'phone_number'  => '081200000035',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'sri.yuliani@guru.sch.id',
                'nip'           => '199007142022212013',
                'name'          => 'Sri Yuliani, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1990-07-14',
                'phone_number'  => '081200000036',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'siti.qomariyah@guru.sch.id',
                'nip'           => '198405252022212026',
                'name'          => 'Siti Qomariyah, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1984-05-25',
                'phone_number'  => '081200000037',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'yana.soviyana@guru.sch.id',
                'nip'           => '198104282022211006',
                'name'          => 'Yana Soviyana, S.E.',
                'gender'        => 'L',
                'date_of_birth' => '1981-04-28',
                'phone_number'  => '081200000038',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'mahani.gunawan@guru.sch.id',
                'nip'           => '199511012022212012',
                'name'          => 'Mahani Gunawan, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1995-11-01',
                'phone_number'  => '081200000039',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'neni.rahmawati@guru.sch.id',
                'nip'           => '199303072022212009',
                'name'          => 'Neni Rahmawati, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1993-03-07',
                'phone_number'  => '081200000040',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'aning.nurganah@guru.sch.id',
                'nip'           => '199711272022212002',
                'name'          => 'Aning Nurganah, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1997-11-27',
                'phone_number'  => '081200000041',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'sintiya.nuri.rosmalia@guru.sch.id',
                'nip'           => '199610102022212009',
                'name'          => 'Sintiya Nuri Rosmalia, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1996-10-10',
                'phone_number'  => '081200000042',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'imas.dewi.ariyanti@guru.sch.id',
                'nip'           => '199707182022212004',
                'name'          => 'Imas Dewi Ariyanti, S.Kom.',
                'gender'        => 'P',
                'date_of_birth' => '1997-07-18',
                'phone_number'  => '081200000043',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'fahmi.agniyatu.rahman@guru.sch.id',
                'nip'           => '199708242022211001',
                'name'          => 'Fahmi Agniyatu Rahman, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1997-08-24',
                'phone_number'  => '081200000044',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'acep.muhammad.sholeh@guru.sch.id',
                'nip'           => '199409152022211004',
                'name'          => 'Acep Muhammad Sholeh, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1994-09-15',
                'phone_number'  => '081200000045',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'dewi.rosita@guru.sch.id',
                'nip'           => '198507132022212025',
                'name'          => 'Dewi Rosita, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1985-07-13',
                'phone_number'  => '081200000046',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'ika.hasanah@guru.sch.id',
                'nip'           => '198601122022212047',
                'name'          => 'Ika Hasanah, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1986-01-12',
                'phone_number'  => '081200000047',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'deasy.putri.lestari@guru.sch.id',
                'nip'           => '198612132022212017',
                'name'          => 'Deasy Putri Lestari, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1986-12-13',
                'phone_number'  => '081200000048',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'devi.rodiana@guru.sch.id',
                'nip'           => '198712232022211009',
                'name'          => 'Devi Rodiana, S.T.',
                'gender'        => 'L',
                'date_of_birth' => '1987-12-23',
                'phone_number'  => '081200000049',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'pia.amanda.nurhusni@guru.sch.id',
                'nip'           => '198812292022212007',
                'name'          => 'Pia Amanda Nurhusni, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1988-12-29',
                'phone_number'  => '081200000050',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'yusef.abdul.aziz@guru.sch.id',
                'nip'           => '198911282022211010',
                'name'          => 'Yusef Abdul Aziz, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1989-11-28',
                'phone_number'  => '081200000051',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'deslita.seniatsaani@guru.sch.id',
                'nip'           => '199112052022212008',
                'name'          => 'Deslita Seniatsaani, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1991-12-05',
                'phone_number'  => '081200000052',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'tenia.octaviana@guru.sch.id',
                'nip'           => '199210102022212015',
                'name'          => 'Tenia Octaviana, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1992-10-10',
                'phone_number'  => '081200000053',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'neri.sondari@guru.sch.id',
                'nip'           => '199501262022212017',
                'name'          => 'Neri Sondari, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1995-01-26',
                'phone_number'  => '081200000054',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'imas.maesaroh@guru.sch.id',
                'nip'           => '199609292022212018',
                'name'          => 'Imas Maesaroh, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1996-09-29',
                'phone_number'  => '081200000055',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'yeni.mulyaningsih@guru.sch.id',
                'nip'           => '198209122023212017',
                'name'          => 'Yeni Mulyaningsih, S.Si.',
                'gender'        => 'P',
                'date_of_birth' => '1982-09-12',
                'phone_number'  => '081200000056',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'amirudin@guru.sch.id',
                'nip'           => '198605012023211012',
                'name'          => 'Amirudin, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1986-05-01',
                'phone_number'  => '081200000057',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'elwin.ar@guru.sch.id',
                'nip'           => '199205062023211017',
                'name'          => 'Elwin A.R., S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1992-05-06',
                'phone_number'  => '081200000058',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'wiana.yulian@guru.sch.id',
                'nip'           => '199207152023212039',
                'name'          => 'Wiana Yulian, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1992-07-15',
                'phone_number'  => '081200000059',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'julia.meliani.rosadi@guru.sch.id',
                'nip'           => '199505262023212023',
                'name'          => 'Julia Meliani Rosadi, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1995-05-26',
                'phone_number'  => '081200000060',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'ratna.nur.indah.sari@guru.sch.id',
                'nip'           => '198709112023212031',
                'name'          => 'Ratna Nur Indah Sari, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1987-09-11',
                'phone_number'  => '081200000061',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'suci.azmiyati@guru.sch.id',
                'nip'           => '198303072023212019',
                'name'          => 'Suci Azmiyati, S.Pd.I.',
                'gender'        => 'P',
                'date_of_birth' => '1983-03-07',
                'phone_number'  => '081200000062',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'sahri.agustian@guru.sch.id',
                'nip'           => '198303072023211002',
                'name'          => 'Sahri Agustian, S.Pd.I.',
                'gender'        => 'L',
                'date_of_birth' => '1983-03-07',
                'phone_number'  => '081200000063',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'harini@guru.sch.id',
                'nip'           => '197806052023212018',
                'name'          => 'Harini, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1978-06-05',
                'phone_number'  => '081200000064',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'agung.sofiyani@guru.sch.id',
                'nip'           => '199206122024212036',
                'name'          => 'Agung Sofiyani, S.E.',
                'gender'        => 'P',
                'date_of_birth' => '1992-06-12',
                'phone_number'  => '081200000065',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'ai.siti.munawaroh@guru.sch.id',
                'nip'           => '199502082024212017',
                'name'          => 'Ai Siti Munawaroh, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1995-02-08',
                'phone_number'  => '081200000066',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'anis.kurly@guru.sch.id',
                'nip'           => '199705152024212025',
                'name'          => 'Anis Kurly, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1997-05-15',
                'phone_number'  => '081200000067',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'arie.iman.maulani@guru.sch.id',
                'nip'           => '198910182024211007',
                'name'          => 'Arie Iman Maulani, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1989-10-18',
                'phone_number'  => '081200000068',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'arinaryani.suryani@guru.sch.id',
                'nip'           => '199504052024212034',
                'name'          => 'Arinaryani Suryani, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1995-04-05',
                'phone_number'  => '081200000069',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'jenal.mutaqin@guru.sch.id',
                'nip'           => '199206232024211010',
                'name'          => 'Jenal Mutaqin, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1992-06-23',
                'phone_number'  => '081200000070',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'dadi.rusyadi@guru.sch.id',
                'nip'           => '198104182024211005',
                'name'          => 'Dadi Rusyadi, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1981-04-18',
                'phone_number'  => '081200000071',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'desty.sobaryantini@guru.sch.id',
                'nip'           => '199112142024212028',
                'name'          => 'Desty Sobaryantini, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1991-12-14',
                'phone_number'  => '081200000072',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'fitria.agustina@guru.sch.id',
                'nip'           => '197908232024212005',
                'name'          => 'Fitria Agustina, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1979-08-23',
                'phone_number'  => '081200000073',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'herna.novitasari@guru.sch.id',
                'nip'           => '199506302024212029',
                'name'          => 'Herna Novitasari, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1995-06-30',
                'phone_number'  => '081200000074',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'maman.nurohman@guru.sch.id',
                'nip'           => '198508132024211006',
                'name'          => 'Maman Nurohman, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1985-08-13',
                'phone_number'  => '081200000075',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'meta.nur.mawaty@guru.sch.id',
                'nip'           => '198503072024212009',
                'name'          => 'Meta Nur Mawaty, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1985-03-07',
                'phone_number'  => '081200000076',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'riris.sri.budiyanti@guru.sch.id',
                'nip'           => '197405042024212003',
                'name'          => 'Riris Sri Budiyanti, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1974-05-04',
                'phone_number'  => '081200000077',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'wiliandini@guru.sch.id',
                'nip'           => '198202022024212016',
                'name'          => 'Wiliandini, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1982-02-02',
                'phone_number'  => '081200000078',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'yeni.maryani@guru.sch.id',
                'nip'           => '197811172024212006',
                'name'          => 'Yeni Maryani, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1978-11-17',
                'phone_number'  => '081200000079',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'muhamad.afrizal@guru.sch.id',
                'nip'           => '199704272024211007',
                'name'          => 'Muhamad Afrizal, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1997-04-27',
                'phone_number'  => '081200000080',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'aziz.muslim@guru.sch.id',
                'nip'           => '197906232025211006',
                'name'          => 'Aziz Muslim, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1979-06-23',
                'phone_number'  => '081200000081',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'zakiatunnisa.iswahyudi@guru.sch.id',
                'nip'           => '199202142025212011',
                'name'          => 'Zakiatunnisa Iswahyudi, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1992-02-14',
                'phone_number'  => '081200000082',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'siti.nurasyiah@guru.sch.id',
                'nip'           => '199506162025212010',
                'name'          => 'Siti Nurasyiah, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1995-06-16',
                'phone_number'  => '081200000083',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'irfan.nur.muttaqin@guru.sch.id',
                'nip'           => '199305202023211006',
                'name'          => 'Irfan Nur Muttaqin, S.Pd.I.',
                'gender'        => 'L',
                'date_of_birth' => '1993-05-20',
                'phone_number'  => '081200000084',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'nina@guru.sch.id',
                'nip'           => '198609232025212079',
                'name'          => 'Nina, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1986-09-23',
                'phone_number'  => '081200000085',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'dela.hikmatul.ambia@guru.sch.id',
                'nip'           => '199005042025212167',
                'name'          => 'Hj. Dela Hikmatul Ambia, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1990-05-04',
                'phone_number'  => '081200000086',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'dini.apriani.nurramdan@guru.sch.id',
                'nip'           => '199004092025212141',
                'name'          => 'Dini Apriani Nurramdan, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1990-04-09',
                'phone_number'  => '081200000087',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'miming.miptahudin@guru.sch.id',
                'nip'           => '198010262025211052',
                'name'          => 'Miming Miptahudin, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1980-10-26',
                'phone_number'  => '081200000088',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'tresna.yuniawati@guru.sch.id',
                'nip'           => '199008152025212159',
                'name'          => 'Tresna Yuniawati, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1990-08-15',
                'phone_number'  => '081200000089',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'arif.zapar.sidik@guru.sch.id',
                'nip'           => '198909182025211000',
                'name'          => 'Arif Zapar Sidik, S.T.',
                'gender'        => 'L',
                'date_of_birth' => '1989-09-18',
                'phone_number'  => '081200000090',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'jajang.ikbal.herlianto@guru.sch.id',
                'nip'           => '199602022025211150',
                'name'          => 'Jajang Ikbal Herlianto, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1996-02-02',
                'phone_number'  => '081200000091',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'ervin.maulana.herdiansyah@guru.sch.id',
                'nip'           => '199606272025211116',
                'name'          => 'Ervin Maulana Herdiansyah, A.Md.',
                'gender'        => 'L',
                'date_of_birth' => '1996-06-27',
                'phone_number'  => '081200000092',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'dhinda.aghita.mahardhika@guru.sch.id',
                'nip'           => '199508162025212000',
                'name'          => 'Dhinda Aghita Mahardhika, S.Pd.',
                'gender'        => 'P',
                'date_of_birth' => '1995-08-16',
                'phone_number'  => '081200000093',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'maulina.fajrin@guru.sch.id',
                'nip'           => '199806252025212000',
                'name'          => 'Maulina Fajrin, S.Par.',
                'gender'        => 'P',
                'date_of_birth' => '1998-06-25',
                'phone_number'  => '081200000094',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'iqbal.fauzi.lisyanto@guru.sch.id',
                'nip'           => '199806252025212001',
                'name'          => 'Iqbal Fauzi Lisyanto, S.Par.',
                'gender'        => 'L',
                'date_of_birth' => '1998-06-25',
                'phone_number'  => '081200000095',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'angga.febrian.pratama@guru.sch.id',
                'nip'           => '199902022025211076',
                'name'          => 'Angga Febrian Pratama, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1999-02-02',
                'phone_number'  => '081200000096',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
            [
                'email'         => 'befi.apriansyah@guru.sch.id',
                'nip'           => '199204222025211151',
                'name'          => 'Befi Apriansyah, S.Pd.',
                'gender'        => 'L',
                'date_of_birth' => '1992-04-22',
                'phone_number'  => '081200000097',
                'address'       => 'Jl. Jenderal Sudirman, Ciamis',
                'department'    => [],
                'subjects'      => [],
            ],
        ];

        foreach ($teachers as $teacherData) {
            $user = User::updateOrCreate(
                ['email' => $teacherData['email']],
                [
                    'password'    => Hash::make($teacherData['nip']),
                    'role'        => 'teacher',
                    'is_active'   => true,
                    'first_login' => true,
                ]
            );

            $teacher = Teacher::updateOrCreate(
                ['nip' => $teacherData['nip']],
                [
                    'user_id'       => $user->id,
                    'name'          => $teacherData['name'],
                    'gender'        => $teacherData['gender'],
                    'date_of_birth' => $teacherData['date_of_birth'],
                    'phone_number'  => $teacherData['phone_number'],
                    'address'       => $teacherData['address'],
                    'department'    => $teacherData['department'],
                ]
            );

            $subjectIds = Subject::whereIn('name', $teacherData['subjects'])
                ->pluck('id')
                ->all();

            if (!empty($subjectIds)) {
                $teacher->subjects()->syncWithoutDetaching($subjectIds);
            }
        }

        $this->command->info('Teacher seeding completed: 97 guru SMKN 1 Ciamis.');
    }
}