[supervisord]
nodaemon=true

[program:frankenphp]
command=php -d variables_order=EGPCS /app/artisan octane:start --server=frankenphp --host=0.0.0.0 --admin-port=2019 --port=80
autostart=true
autorestart=true
stdout_logfile=/app/storage/logs/frankenphp.log
stderr_logfile=/app/storage/logs/frankenphp-error.log

[program:laravel-queue]
process_name=%(program_name)s_%(process_num)02d
command=php /app/artisan queue:work --tries=3
autostart=true
autorestart=true
numprocs=2
redirect_stderr=true
stdout_logfile=/app/storage/logs/laravel-queue.log
