name: staging.yml
on:
  push:
    branches:
      - staging

jobs:
  deploy-staging:
    runs-on: home-devapps

    steps:
      - name: pull latest changes
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "${{ vars.STAGING_ENV }}" > .env

      - name: Create Compose file
        run: |
          echo "${{ vars.STAGING_DOCKER }}" > docker-compose.staging.yml

      - name: Deploy to Staging
        run: |
          docker compose -f docker-compose.staging.yml up -d --build

      - name: Clean up old images
        run: |
          docker system prune -f
